apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opa-configmap-modifier
  namespace: enforcement
  labels:
    type: opa
    function: admission-control
    layer: cluster
    version: v1
  
roleRef:
  kind: Role
  name: configmap-modifier
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system:serviceaccounts:opa
  apiGroup: rbac.authorization.k8s.io