apiVersion: v1
kind: Service
metadata:
  name: opa
  namespace: enforcement
  labels:
    type: opa
    function: admission-control
    layer: cluster
    version: v1
spec:
  selector:
    app: opa
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443