apiVersion: v1
kind: Service
metadata:
  name: kibana-loadbalancer
  namespace: kube-monitor
  labels:
    type: kibana
    function: external-access
    layer: cluster
    version: v1
spec:
  selector:
    app: kibana
  ports:
  - name: http
    port: 80
    targetPort: 5601
  type: LoadBalancer