apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: kube-monitor
  labels:
    app: kibana
    type: kibana
    function: monitoring
    layer: cluster
    version: v1
spec:
  ports:
  - port: 5601
  selector:
    app: kibana