apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-loadbalancer
  namespace: kube-monitor
  labels:
    type: elasticsearch
    function: external-access
    layer: cluster
    version: v1
spec:
  selector:
    app: elastic-search
  ports:
  - name: http
    port: 80
    targetPort: 9200
  type: LoadBalancer