apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: kube-monitor
  labels:
    type: elasticsearch
    function: monitoring
    layer: cluster
    version: v1
spec:
  clusterIP: None
  selector:
    app: elastic-search
  ports:
  - name: transport
    port: 9300